# Generated by Django 4.1 on 2022-08-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('company_code', models.CharField(max_length=50)),
                ('strength', models.IntegerField(max_length=1000)),
                ('web_site', models.CharField(max_length=250)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
